openapi: 3.0.3
info:
  title: Horoscope v2 graphql
  version: 1.0.0
servers:
  - url: https://indexer-v2.staging.aurascan.io
  - url: https://indexer-v2.dev.aurascan.io
tags:
  - name: cw20
paths:
  /api/v1/graphiql:
    post:
      tags:
        - account
      summary: Query account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/account'
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    account:
      type: object
      properties:
        operationName:
          type: string
          example: account
          description: query name
        query:
          type: string
          example: "query account($limit: Int = 10, $address: String = null) { euphoria { account(limit: $limit, where: {address: {_eq: $address}}) { account_number address balances pubkey sequence spendable_balances type updated_at created_at } } }"
          description: Graphql query
        variables:
          type: object
          description: Variable in query
          example:
            limit: 10
            address: null
            
            
                  
            
          
            
