openapi: 3.0.3
info:
  title: Horoscope v2 graphql
  version: 1.0.0
servers:
  - url: https://indexer-v2.staging.aurascan.io
  - url: https://indexer-v2.dev.aurascan.io
tags:
  - name: cw20
paths:
  /api/v1/graphiql:
    post:
      tags:
        - cw20
      summary: Query cw20 activity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cw20activity'
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    cw20activity:
      type: object
      properties:
        operationName:
          type: string
          example: cw20activity
          description: query name
        query:
          type: string
          example: "query cw20activity($limit: Int = 10, $contractAddress: String = null) { euphoria { cw20_activity(where: {cw20_contract: {smart_contract: {address: {_eq: $contractAddress}}}}, limit: $limit) { action amount from height sender to smart_contract_event_id id } } }"
          description: Graphql query
        variables:
          type: object
          description: Variable in query
          example:
            limit: 10
            contractAddress: aura17k2jq9dhq4kqgrtdrzt2qs0zy45cw0lmp3tfxysp7cwh5nxfg24st7ndc8
            
            
                  
            
          
            
